### ISSUE TITLE
MusixMatch Query

### ISSUE THREAD

**Issue by greg-a** [psu23/SoundtrackFinder#9]
Need to figure out how to get the lyrics to show up on the page in the correct format. Right now it is displaying the entire response from the MusixMatch query.

**Comment by psu23** [comment]
Ah okay, I'll look into that in a bit. Currently trying to prevent the queue from loading in a random order anytime the page loads. I think it has something to do with ajax loops within for loops posing issues so I think I will separate the for loop and ajax into two functions

**Comment by greg-a** [comment]
Nicely done, thanks!
